### ISSUE TITLE
Streamlining / implementing interface for Chefling configuration.

### ISSUE THREAD

**Issue by Joepeman** [cookingfox/chefling-di-java#2]
Hi Abel,

Setting up a new project using Chefling made me realize there is no current convention for Chefling (application) configuration. For example, from the Main if you start using the Chefling Container it's necessary to configure your class mappings. Experience shows these mappings often result in enormous bulks of text. After a while we've came up with the so-called 'CheflingConfig' class that wraps up all the Chefling application configuration steps specifically necessary for your application.

I think it would be a good thing if we introduce some sort of CheflingBuilder, which provides the following basic methods (example):
- **configureLibraries**( iCheflingLibraryMap libraryMap )
- **configureApplication**( iCheflingApplicationMap applicationMap )
- **run**()

A new bird in the nest is '**run()**', which is the last method to call after configuring Chefling. I think it would not only provide a good option for structuring the Container configuration, but it would also streamline the problem of 'where do I kick-off my app'.

To clarify my idea, in your Main you could do something like this:

`Chefling`
`.configureLibraries(new MyLibraryMap())`
`.configureApplication(new MyApplicationMap())`
`.configureInitialization(new MyAppInitOrder())`
`.run();`

Let me know what you think!

Thanks,
Joep

Note: edited some naming stuff after thinking about it.

**Comment by cookingfox** [comment]
Hi Joep,

Thanks for the feedback! I've added a Builder implementation, that was added with version 4.0.4.

Usage:

``` java
Container container = new Chefling.Builder()
  .add(new LibraryConfig())
  .add(new AppConfig())
  .add(new InitializationConfig())
  .build();
```

These configurations are applied in the order they are added. Take a look at the source code and unit tests for more info.

Thanks,
Abel
